### ISSUE TITLE
build-all.sh After the completion of the new macOS application reference libRTMP_macOS.framework error

### ISSUE THREAD

**Issue by janZhao** [Norod/libRTMP-iOS-macOS#1]
dyld: Library not loaded: @rpath/libRTMP_macOS.framework/Versions/A/libRTMP_macOS
  Referenced from: /Users/jyd/Library/Developer/Xcode/DerivedData/AirScreen-ejqlcxibkyarcbgyorsbuorpuxga/Build/Products/Debug/AirScreen.app/Contents/MacOS/AirScreen
  Reason: image not found

**Comment by Norod** [comment]
@janZhao Thank you for this report, I'll try and have a look on Monday or Tuesday

**Comment by janZhao** [comment]
你好 我想用librtmp-macOS 捕获桌面 然后以rtmp形式推送到nginx流媒体服务器，请问如何使用呢？
  [EDITED, Google Translate]
Hello I would like to use librtmp-macOS capture desktop and then rtmp form to push to nginx streaming media server, how to use it?

**Comment by Norod** [comment]
@janZhao I have made an updated version. Please run the "Build All" script.
You should then use the verifyLinkToLib project inside the platform folder to verify that linkage happens.
You can put breakpoints in AppDelegate to see how the RTMP context is created, initialized and destroyed. This repo is only for building a dynamic framework wrapper for libRTMP for iOS and macOS, if you need help in using libRTMP, you should seek help in other relevant forums.
Thank you
